name: Linux Build
on: push
jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: e8b88cf879fc378ac512a3f41044145a39b32adc
    - name: Install dependencies
      run: |  
        sudo apt update
        sudo apt install -y git cmake make ninja-build gcc g++ python3 gawk bison flex libssl-dev libmpfr-dev libmpc-dev libgmp-dev texinfo wget unzip
        wget https://github.com/reactos/RosBE/archive/refs/heads/master.zip -O rosbe.zip
        unzip rosbe.zip
        cd RosBE-master
        sudo ./ninja.sh install
        cd ..
        mkdir build
        cd build
        cmake .. -G Ninja
        ninja

