name: Linux Build
on: push
jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: e8b88cf879fc378ac512a3f41044145a39b32adc
    - name: Install dependencies
      run: |  
        sudo apt-get update
        sudo apt-get install -y git cmake make ninja-build gcc g++ python3 gawk bison flex libssl-dev libmpfr-dev libmpc-dev libgmp-dev texinfo wget unzip
        sudo add-apt-repository ppa:reactos/rosbe-unix
        sudo apt install rosbe-unix
   

